---
- name: Create a virtual machine
  hosts: localhost
  connection: local
  vars:
    name_resource_group: dev-rg
    name_virtual_network: dev-vnet
    name_subnet: dev-sn
    name_network_security_group: dev-nsg
    name_public_ip: dev-pip-01
    name_network_interface_card: dev-nic-01
    user: << username >>
    pub_key: ssh-rsa << public key >>
    name_virtual_machine: dev-vm-01
    name_vm_size: Standard_B1s
    name_image_offer: CentOS
    name_image_publisher: OpenLogic
    name_image_sku: '7.5'
    name_image_version: latest
  
  tasks:
  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: "{{ name_resource_group }}"
      allocation_method: Static
      name: "{{ name_public_ip }}"

# throws a [DEPRECATION WARNING] review for future proofing

  - name: Create virtual network inteface card
    azure_rm_networkinterface:
      resource_group: "{{ name_resource_group }}"
      name: "{{ name_network_interface_card }}"
      virtual_network: "{{ name_virtual_network }}"
      subnet: "{{ name_subnet }}"
      public_ip_name: "{{ name_public_ip }}"
      security_group: "{{ name_network_security_group }}"

  - name: Create virtual machine
    azure_rm_virtualmachine:
      resource_group: "{{ name_resource_group }}"
      name: "{{ name_virtual_machine }}"
      vm_size: "{{ name_vm_size }}"
      admin_username: "{{ user }}"
      ssh_password_enabled: false
      ssh_public_keys:
        - path: "/home/{{ user }}/.ssh/authorized_keys"
          key_data: "{{ pub_key }}"
      network_interfaces: "{{ name_network_interface_card }}"
      image:
        offer: "{{ name_image_offer }}"
        publisher: "{{ name_image_publisher }}"
        sku: "{{ name_image_sku }}"
        version: "{{ name_image_version }}"