---
- name: Set up primatives for VM
  hosts: localhost
  connection: local
  vars:
    name_resource_group: dev-rg
    name_virtual_network: dev-vnet
    name_network_security_group: dev-nsg
    name_network_interface_card: dev-nic-01
    name_public_ip: dev-pip-01
#    name_subnet: dev-sn
  tasks:
  - name: Create resource group
    azure_rm_resourcegroup:
      name: "{{ name_resource_group }}"
      location: centralus

  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: "{{ name_resource_group }}"
      name: "{{ name_virtual_network }}"
      address_prefixes: "10.0.0.0/16"

#  - name: Add subnet
#    azure_rm_subnet:
#      resource_group: "{{ name_resource_group }}"
#      name: "{{ name_subnet }}"
#      address_prefix: "10.0.1.0/24"
#      virtual_network: "{{ name_virtual_network }}"

  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: "{{ name_resource_group }}"
      allocation_method: Static
      name: "{{ name_public_ip }}"

  - name: Create Network Security Group that allows SSH
    azure_rm_securitygroup:
      resource_group: "{{ name_resource_group }}"
      name: "{{ name_network_security_group }}"
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 1001
          direction: Inbound

# throws a [DEPRECATION WARNING] review for future proofing

  - name: Create virtual network inteface card
    azure_rm_networkinterface:
      resource_group: "{{ name_resource_group }}"
      name: "{{ name_network_interface_card }}"
      virtual_network: "{{ name_virtual_network }}"
#      subnet: "{{ name_subnet }}"
      public_ip_name: "{{ name_public_ip }}"
      security_group: "{{ name_network_security_group }}"